version: '3.4'

services:
  detree:
    image: ${DOCKER_REGISTRY-}detree
    container_name: detreeapi
    depends_on:
      - dtpostgres
    build:
      context: .
      dockerfile: src/detree/Dockerfile
    ports:
    - 5225:80
    environment:
      ASPNETCORE_ENVIRONMENT": "Development"
      DT_ConnectionStrings__DB_CONNECTION_STRING: "host=dtpostgres;port=5432;database=dtdb;username=dtuser;password=dtpass"
    networks:
      - detreeapi-dev

  authserver:
    image: ${DOCKER_REGISTRY-}authserver
    container_name: authserver
    depends_on:
      - dtpostgres
    build:
      context: .
      dockerfile: auth/AuthServer/Dockerfile
    ports:
    - 5230:80
    environment:
      ASPNETCORE_ENVIRONMENT": "Development"
      AS_ConnectionStrings__DB_CONNECTION_STRING: "host=dtpostgres;port=5432;database=dtdb;username=dtuser;password=dtpass"
    networks:
      - detreeapi-dev

  dtpostgres:
    image: postgres:latest
    container_name: dtpostgres
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data      
    environment:
      ASPNETCORE_ENVIRONMENT": "Development"
      POSTGRES_USER: "dtuser"
      POSTGRES_PASSWORD: "dtpass"
      POSTGRES_DB: "dtdb"
    networks:
      - detreeapi-dev

volumes:
  db_volume:

networks:
  detreeapi-dev:
    driver: bridge 