version: '3.4'

services:
  detree:
    image: detree:latest
    container_name: detreeapi
    depends_on:
      - dtpostgres
    build:
      context: .
      dockerfile: src/detree/Dockerfile
    environment:
      DT_ConnectionStrings__DB_CONNECTION_STRING: "host=45.84.224.59;port=5432;database=dtdb;username=dtuser;password=dtpass"
      VIRTUAL_HOST: api.detree.ru
      LETSENCRYPT_HOST: api.detree.ru
      LETSENCRYPT_EMAIL: mail@detree.ru

  authserver:
    image: authserver:latest
    container_name: authserver
    depends_on:
      - dtpostgres
    build:
      context: .
      dockerfile: auth/AuthServer/Dockerfile
    environment:
      AS_ConnectionStrings__DB_CONNECTION_STRING: "host=45.84.224.59;port=5432;database=dtdb;username=dtuser;password=dtpass"
      VIRTUAL_HOST: auth.detree.ru
      LETSENCRYPT_HOST: auth.detree.ru
      LETSENCRYPT_EMAIL: mail@detree.ru

  dtpostgres:
    image: postgres:latest
    container_name: dtpostgres
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data      
    environment:
      POSTGRES_USER: "dtuser"
      POSTGRES_PASSWORD: "dtpass"
      POSTGRES_DB: "dtdb"

volumes:
  db_volume:

networks:
  default:
    external:
      name: webproxy 